version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  rails:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE_URL=postgres://postgres:password@postgres:5432/postgres
      - REDIS_URL=redis://redis:6379
    volumes:
      - .:/app

volumes:
  postgres_data: